# Generated by Django 3.2.7 on 2022-11-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryMonitorStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_text', models.CharField(max_length=1000)),
                ('curr_date_time', models.DateTimeField(verbose_name='Status time')),
            ],
        ),
        migrations.CreateModel(
            name='logRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_unlock_text', models.CharField(max_length=100)),
                ('last_unlock_time', models.DateTimeField(verbose_name='Last unlock time')),
            ],
        ),
        migrations.CreateModel(
            name='Reset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reset_intstruction', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=2000)),
                ('password', models.TextField(default='', max_length=2000)),
            ],
        ),
    ]
