# Generated by Django 3.2.7 on 2022-11-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TapBoxMain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reset',
            name='reset_button',
            field=models.IntegerField(default=1),
        ),
    ]
