# Generated by Django 3.2.7 on 2022-11-22 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TapBoxMain', '0003_alter_reset_reset_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='batterymonitorstatus',
            name='battery_text',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
